---
id: Form
name: Form
full: Form library
description: A library that provides form rendering, validation, and other functionality.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Form
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha5
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/core: ^3
      horde/date: ^3
      horde/exception: ^3
      horde/mail: ^3
      horde/mime: ^3
      horde/nls: ^3
      horde/token: ^3
      horde/translation: ^3
      horde/util: ^3
    ext:
      json: '*'
autoload:
  classmap:
    - lib/
